DEFAULT_IGNORE_DIRS: set[str] = {
    ".git",
    "node_modules",
    "vendor",
    "dist",
    "build",
    ".next",
    "target",
    "__pycache__",
    ".venv",
    "venv",
    "coverage",
    "outputs",
}

NOISY_FILE_SUFFIXES: set[str] = {
    ".log",
    ".out",
    ".err",
    ".jar",
    ".war",
    ".ear",
    ".class",
    ".zip",
    ".gz",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".pdf",
    ".db",
    ".sqlite",
}

LANGUAGE_BY_EXTENSION: dict[str, str] = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".java": "java",
    ".go": "go",
    ".rb": "ruby",
    ".php": "php",
    ".cs": "csharp",
    ".xml": "xml",
    ".jsp": "jsp",
    ".jspx": "jsp",
    ".properties": "config",
    ".conf": "config",
    ".bat": "batch",
    ".cmd": "batch",
    ".sh": "shell",
    ".sql": "sql",
    ".yml": "yaml",
    ".yaml": "yaml",
    ".json": "json",
    ".toml": "toml",
    ".md": "markdown",
}
